# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0002_group_project'),
    ]

    operations = [

    ]
