# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0001_initial'),
        ('GroupsApp', '0003_auto_20161202_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.Project'),
        ),
    ]
