# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsApp', '0002_specialty'),
        ('ProjectsApp', '0003_auto_20161203_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(related_name='languages', to='SkillsApp.Skill'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='specialty',
        ),
        migrations.AddField(
            model_name='project',
            name='specialty',
            field=models.ManyToManyField(related_name='specialty', to='SkillsApp.Skill'),
        ),
    ]
