# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0004_auto_20161207_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='specialty',
            field=models.ManyToManyField(related_name='specialty', to='SkillsApp.Specialty'),
        ),
    ]
