# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0006_auto_20161204_1806'),
        ('ProjectsApp', '0005_auto_20161207_0329'),
    ]

    operations = [
    ]
