# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0006_project_takenby'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='takenBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takenBy', to='GroupsApp.Group', default=0),
        ),
    ]
