# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsApp', '0002_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='descriptor',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='descriptor',
        ),
    ]
