# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
