# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0006_engineer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineer',
            old_name='alma_mater',
            new_name='university',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='about',
        ),
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='usertype',
            field=models.CharField(blank=True, choices=[('STU', 'Student'), ('PRO', 'Professor'), ('ENG', 'Engineer')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
