# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0012_auto_20161126_0723'),
    ]

    operations = [

    ]
