# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0021_auto_20161127_0107'),
    ]

    operations = [

    ]
