# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0024_auto_20161127_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='univ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
