# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0025_auto_20161127_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='univ',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
