# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0027_myuser_joined_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='joined_university',
            field=models.BooleanField(default=True),
        ),
    ]
