# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0029_auto_20161127_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='joined_university',
            field=models.BooleanField(),
        ),
    ]
