# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0004_auto_20161108_1557'),
        ('AuthenticationApp', '0032_auto_20161129_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='joined_university',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='univ',
        ),
        migrations.AddField(
            model_name='engineer',
            name='univ',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='univ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
        migrations.AddField(
            model_name='student',
            name='univ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
