# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0033_auto_20161129_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='skills',
            field=models.CharField(blank=True, choices=[('JAV', 'Java'), ('AND', 'Android'), ('C', 'C'), ('IOS', 'iOS'), ('SQL', 'SQL'), ('JS', 'JavaScript'), ('C#', 'C#'), ('RUB', 'Ruby'), ('HTM', 'HTML/CSS'), ('C++', 'C++'), ('PYT', 'Python'), ('WEB', 'Web Development'), ('PHP', 'PHP')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='yearsProgramming',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
