# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0034_auto_20161201_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='about',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='skills',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
