# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsApp', '0001_initial'),
        ('AuthenticationApp', '0035_auto_20161201_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='skills',
        ),
        migrations.AddField(
            model_name='myuser',
            name='skills',
            field=models.ManyToManyField(to='SkillsApp.Skill'),
        ),
    ]
