# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsApp', '0002_specialty'),
        ('AuthenticationApp', '0036_auto_20161207_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='specialty',
            field=models.ManyToManyField(to='SkillsApp.Specialty'),
        ),
    ]
