# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0037_myuser_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='skills',
            field=models.ManyToManyField(default=None, to='SkillsApp.Skill'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='specialty',
            field=models.ManyToManyField(default=None, to='SkillsApp.Specialty'),
        ),
    ]
