# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0001_initial'),
        ('AuthenticationApp', '0038_auto_20161207_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CompaniesApp.Company'),
        ),
    ]
