# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookmarksApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user_id',
        ),
    ]
