# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0005_auto_20161207_0329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookmarksApp', '0002_auto_20161208_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.Project'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
